authors:
  # author identifier (GitHub in this case)
  genesis-writing:
    name: Fran Roman
    description: Technical Writer
    avatar: https://avatars.githubusercontent.com/u/93626701?v=4
    url: https://github.com/genesis-writing